/* =====================================================================
   ECommerce - Specialty Coffee Shop
   Core MVP schema  |  Microsoft SQL Server (T-SQL)
   Source: PTTK data model (section 10).

   Naming convention: UPPER_SNAKE_CASE for tables & columns (Oracle-style).
   Audit columns on every table: CREATED_AT / CREATED_BY / UPDATED_AT / UPDATED_BY
     - *_BY hold the acting user's Id (UNIQUEIDENTIFIER), NULL = system/guest.
     - Kept as plain audit metadata (no FK) to avoid extra cascade paths.

   NOTE: EF Core Code-First defaults to PascalCase. To keep this naming you
   must either map each entity (ToTable/HasColumnName) or use the
   EFCore.NamingConventions package: optionsBuilder.UseUpperSnakeCaseNamingConvention().
   Run batches in order (FK dependencies).
   ===================================================================== */

-- CREATE DATABASE ECommerce;
-- GO
-- USE ECommerce;
-- GO
SET NOCOUNT ON;
GO

/* ---------- 1. USERS ---------- */
CREATE TABLE dbo.USERS
(
    ID                  UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_USERS PRIMARY KEY DEFAULT NEWID(),
    EMAIL               NVARCHAR(256)    NOT NULL,
    PASSWORD_HASH       NVARCHAR(500)    NOT NULL,
    FULL_NAME           NVARCHAR(200)    NOT NULL,
    PHONE               NVARCHAR(20)     NULL,
    ROLE                VARCHAR(20)      NOT NULL CONSTRAINT DF_USERS_ROLE DEFAULT 'Customer',
    IS_EMAIL_VERIFIED   BIT              NOT NULL CONSTRAINT DF_USERS_IS_EMAIL_VERIFIED DEFAULT 0,
    EMAIL_VERIFY_TOKEN  NVARCHAR(200)    NULL,
    EMAIL_VERIFY_EXPIRY DATETIME2        NULL,
    IS_ACTIVE           BIT              NOT NULL CONSTRAINT DF_USERS_IS_ACTIVE DEFAULT 1,
    LOYALTY_POINT       INT              NOT NULL CONSTRAINT DF_USERS_LOYALTY_POINT DEFAULT 0,
    LAST_LOGIN_AT       DATETIME2        NULL,
    CREATED_AT          DATETIME2        NOT NULL CONSTRAINT DF_USERS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY          UNIQUEIDENTIFIER NULL,
    UPDATED_AT          DATETIME2        NULL,
    UPDATED_BY          UNIQUEIDENTIFIER NULL,
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('Customer','Staff','Admin'))
);
GO

/* ---------- 2. CATEGORIES (tree) ---------- */
CREATE TABLE dbo.CATEGORIES
(
    ID         UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CATEGORIES PRIMARY KEY DEFAULT NEWID(),
    PARENT_ID  UNIQUEIDENTIFIER NULL,
    NAME       NVARCHAR(200)    NOT NULL,
    SLUG       NVARCHAR(200)    NOT NULL,
    SORT_ORDER INT              NOT NULL CONSTRAINT DF_CATEGORIES_SORT_ORDER DEFAULT 0,
    IS_ACTIVE  BIT              NOT NULL CONSTRAINT DF_CATEGORIES_IS_ACTIVE DEFAULT 1,
    CREATED_AT DATETIME2        NOT NULL CONSTRAINT DF_CATEGORIES_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY UNIQUEIDENTIFIER NULL,
    UPDATED_AT DATETIME2        NULL,
    UPDATED_BY UNIQUEIDENTIFIER NULL,
    CONSTRAINT UQ_CATEGORIES_SLUG UNIQUE (SLUG),
    CONSTRAINT FK_CATEGORIES_PARENT FOREIGN KEY (PARENT_ID) REFERENCES dbo.CATEGORIES(ID)
);
GO

/* ---------- 3. ADDRESSES ---------- */
CREATE TABLE dbo.ADDRESSES
(
    ID             UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ADDRESSES PRIMARY KEY DEFAULT NEWID(),
    USER_ID        UNIQUEIDENTIFIER NOT NULL,
    RECIPIENT_NAME NVARCHAR(200)    NOT NULL,
    PHONE          NVARCHAR(20)     NOT NULL,
    PROVINCE       NVARCHAR(100)    NOT NULL,
    DISTRICT       NVARCHAR(100)    NOT NULL,
    WARD           NVARCHAR(100)    NULL,
    STREET         NVARCHAR(300)    NOT NULL,
    IS_DEFAULT     BIT              NOT NULL CONSTRAINT DF_ADDRESSES_IS_DEFAULT DEFAULT 0,
    CREATED_AT     DATETIME2        NOT NULL CONSTRAINT DF_ADDRESSES_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY     UNIQUEIDENTIFIER NULL,
    UPDATED_AT     DATETIME2        NULL,
    UPDATED_BY     UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_ADDRESSES_USERS FOREIGN KEY (USER_ID) REFERENCES dbo.USERS(ID) ON DELETE CASCADE
);
GO

/* ---------- 4. COUPONS ---------- */
CREATE TABLE dbo.COUPONS
(
    ID                  UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_COUPONS PRIMARY KEY DEFAULT NEWID(),
    CODE                NVARCHAR(50)     NOT NULL,
    [TYPE]              VARCHAR(20)      NOT NULL,
    VALUE               DECIMAL(18,2)    NOT NULL,
    MIN_ORDER_AMOUNT    DECIMAL(18,2)    NOT NULL CONSTRAINT DF_COUPONS_MIN_ORDER_AMOUNT DEFAULT 0,
    MAX_DISCOUNT_AMOUNT DECIMAL(18,2)    NULL,
    MAX_USAGE           INT              NULL,
    MAX_USAGE_PER_USER  INT              NOT NULL CONSTRAINT DF_COUPONS_MAX_USAGE_PER_USER DEFAULT 1,
    USED_COUNT          INT              NOT NULL CONSTRAINT DF_COUPONS_USED_COUNT DEFAULT 0,
    START_AT            DATETIME2        NOT NULL,
    END_AT              DATETIME2        NOT NULL,
    IS_ACTIVE           BIT              NOT NULL CONSTRAINT DF_COUPONS_IS_ACTIVE DEFAULT 1,
    CREATED_AT          DATETIME2        NOT NULL CONSTRAINT DF_COUPONS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY          UNIQUEIDENTIFIER NULL,
    UPDATED_AT          DATETIME2        NULL,
    UPDATED_BY          UNIQUEIDENTIFIER NULL,
    CONSTRAINT UQ_COUPONS_CODE UNIQUE (CODE),
    CONSTRAINT CK_COUPONS_TYPE CHECK ([TYPE] IN ('Percent','Fixed')),
    CONSTRAINT CK_COUPONS_DATES CHECK (END_AT > START_AT)
);
GO

/* ---------- 5. PRODUCTS ---------- */
CREATE TABLE dbo.PRODUCTS
(
    ID              UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_PRODUCTS PRIMARY KEY DEFAULT NEWID(),
    SLUG            NVARCHAR(200)    NOT NULL,
    NAME            NVARCHAR(300)    NOT NULL,
    DESCRIPTION     NVARCHAR(MAX)    NULL,
    CATEGORY_ID     UNIQUEIDENTIFIER NOT NULL,
    BASE_PRICE      DECIMAL(18,2)    NOT NULL,
    IS_ACTIVE       BIT              NOT NULL CONSTRAINT DF_PRODUCTS_IS_ACTIVE DEFAULT 1,
    IS_DELETED      BIT              NOT NULL CONSTRAINT DF_PRODUCTS_IS_DELETED DEFAULT 0,
    SEO_TITLE       NVARCHAR(200)    NULL,
    SEO_DESCRIPTION NVARCHAR(500)    NULL,
    CREATED_AT      DATETIME2        NOT NULL CONSTRAINT DF_PRODUCTS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY      UNIQUEIDENTIFIER NULL,
    UPDATED_AT      DATETIME2        NULL,
    UPDATED_BY      UNIQUEIDENTIFIER NULL,
    CONSTRAINT UQ_PRODUCTS_SLUG UNIQUE (SLUG),
    CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES dbo.CATEGORIES(ID),
    CONSTRAINT CK_PRODUCTS_BASE_PRICE CHECK (BASE_PRICE >= 0)
);
GO

/* ---------- 6. PRODUCT_VARIANTS ---------- */
CREATE TABLE dbo.PRODUCT_VARIANTS
(
    ID              UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_PRODUCT_VARIANTS PRIMARY KEY DEFAULT NEWID(),
    PRODUCT_ID      UNIQUEIDENTIFIER NOT NULL,
    SKU             NVARCHAR(100)    NOT NULL,
    ATTRIBUTES_JSON NVARCHAR(MAX)    NULL,
    PRICE           DECIMAL(18,2)    NOT NULL,
    COMPARE_PRICE   DECIMAL(18,2)    NULL,
    IMAGE_URL       NVARCHAR(500)    NULL,
    WEIGHT          DECIMAL(10,2)    NULL,
    IS_ACTIVE       BIT              NOT NULL CONSTRAINT DF_PRODUCT_VARIANTS_IS_ACTIVE DEFAULT 1,
    CREATED_AT      DATETIME2        NOT NULL CONSTRAINT DF_PRODUCT_VARIANTS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY      UNIQUEIDENTIFIER NULL,
    UPDATED_AT      DATETIME2        NULL,
    UPDATED_BY      UNIQUEIDENTIFIER NULL,
    CONSTRAINT UQ_PRODUCT_VARIANTS_SKU UNIQUE (SKU),
    CONSTRAINT FK_PRODUCT_VARIANTS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_PRODUCT_VARIANTS_PRICE CHECK (PRICE >= 0)
);
GO

/* ---------- 7. INVENTORIES (1-1 with variant) ---------- */
CREATE TABLE dbo.INVENTORIES
(
    VARIANT_ID  UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_INVENTORIES PRIMARY KEY,
    ON_HAND     INT              NOT NULL CONSTRAINT DF_INVENTORIES_ON_HAND DEFAULT 0,
    RESERVED    INT              NOT NULL CONSTRAINT DF_INVENTORIES_RESERVED DEFAULT 0,
    AVAILABLE   AS (ON_HAND - RESERVED) PERSISTED,
    ROW_VERSION ROWVERSION       NOT NULL,
    CREATED_AT  DATETIME2        NOT NULL CONSTRAINT DF_INVENTORIES_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY  UNIQUEIDENTIFIER NULL,
    UPDATED_AT  DATETIME2        NULL,
    UPDATED_BY  UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_INVENTORIES_VARIANTS FOREIGN KEY (VARIANT_ID) REFERENCES dbo.PRODUCT_VARIANTS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_INVENTORIES_ON_HAND CHECK (ON_HAND >= 0),
    CONSTRAINT CK_INVENTORIES_RESERVED CHECK (RESERVED >= 0 AND RESERVED <= ON_HAND)
);
GO

/* ---------- 8. CARTS ---------- */
CREATE TABLE dbo.CARTS
(
    ID         UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CARTS PRIMARY KEY DEFAULT NEWID(),
    USER_ID    UNIQUEIDENTIFIER NULL,
    SESSION_ID NVARCHAR(200)    NULL,
    COUPON_ID  UNIQUEIDENTIFIER NULL,
    EXPIRES_AT DATETIME2        NULL,
    CREATED_AT DATETIME2        NOT NULL CONSTRAINT DF_CARTS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY UNIQUEIDENTIFIER NULL,
    UPDATED_AT DATETIME2        NULL,
    UPDATED_BY UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_CARTS_USERS FOREIGN KEY (USER_ID) REFERENCES dbo.USERS(ID),
    CONSTRAINT FK_CARTS_COUPONS FOREIGN KEY (COUPON_ID) REFERENCES dbo.COUPONS(ID),
    CONSTRAINT CK_CARTS_OWNER CHECK (USER_ID IS NOT NULL OR SESSION_ID IS NOT NULL)
);
GO

/* ---------- 9. CART_ITEMS ---------- */
CREATE TABLE dbo.CART_ITEMS
(
    ID         UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CART_ITEMS PRIMARY KEY DEFAULT NEWID(),
    CART_ID    UNIQUEIDENTIFIER NOT NULL,
    VARIANT_ID UNIQUEIDENTIFIER NOT NULL,
    QUANTITY   INT              NOT NULL,
    CREATED_AT DATETIME2        NOT NULL CONSTRAINT DF_CART_ITEMS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY UNIQUEIDENTIFIER NULL,
    UPDATED_AT DATETIME2        NULL,
    UPDATED_BY UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_CART_ITEMS_CARTS FOREIGN KEY (CART_ID) REFERENCES dbo.CARTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_ITEMS_VARIANTS FOREIGN KEY (VARIANT_ID) REFERENCES dbo.PRODUCT_VARIANTS(ID),
    CONSTRAINT UQ_CART_ITEMS_CART_VARIANT UNIQUE (CART_ID, VARIANT_ID),
    CONSTRAINT CK_CART_ITEMS_QUANTITY CHECK (QUANTITY > 0)
);
GO

/* ---------- 10. ORDERS ---------- */
CREATE TABLE dbo.ORDERS
(
    ID                    UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ORDERS PRIMARY KEY DEFAULT NEWID(),
    ORDER_NUMBER          VARCHAR(20)      NOT NULL,
    USER_ID               UNIQUEIDENTIFIER NOT NULL,
    STATUS                VARCHAR(20)      NOT NULL CONSTRAINT DF_ORDERS_STATUS DEFAULT 'Pending',
    SUBTOTAL              DECIMAL(18,2)    NOT NULL,
    SHIPPING_FEE          DECIMAL(18,2)    NOT NULL CONSTRAINT DF_ORDERS_SHIPPING_FEE DEFAULT 0,
    DISCOUNT              DECIMAL(18,2)    NOT NULL CONSTRAINT DF_ORDERS_DISCOUNT DEFAULT 0,
    TOTAL                 DECIMAL(18,2)    NOT NULL,
    COUPON_CODE           NVARCHAR(50)     NULL,
    SHIPPING_ADDRESS_JSON NVARCHAR(MAX)    NOT NULL,
    NOTE                  NVARCHAR(500)    NULL,
    PAYMENT_METHOD        VARCHAR(20)      NOT NULL,
    CONFIRMED_AT          DATETIME2        NULL,
    SHIPPED_AT            DATETIME2        NULL,
    DELIVERED_AT          DATETIME2        NULL,
    COMPLETED_AT          DATETIME2        NULL,
    CANCELLED_AT          DATETIME2        NULL,
    CANCEL_REASON         NVARCHAR(500)    NULL,
    ROW_VERSION           ROWVERSION       NOT NULL,
    CREATED_AT            DATETIME2        NOT NULL CONSTRAINT DF_ORDERS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY            UNIQUEIDENTIFIER NULL,
    UPDATED_AT            DATETIME2        NULL,
    UPDATED_BY            UNIQUEIDENTIFIER NULL,
    CONSTRAINT UQ_ORDERS_ORDER_NUMBER UNIQUE (ORDER_NUMBER),
    CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USER_ID) REFERENCES dbo.USERS(ID),
    CONSTRAINT CK_ORDERS_STATUS CHECK (STATUS IN
        ('Pending','Confirmed','Packed','Shipping','Delivered','Completed','Cancelled','Returning','Returned','Refunded')),
    CONSTRAINT CK_ORDERS_PAYMENT_METHOD CHECK (PAYMENT_METHOD IN ('COD','VNPay','MoMo')),
    CONSTRAINT CK_ORDERS_TOTAL CHECK (TOTAL >= 0)
);
GO

/* ---------- 11. ORDER_ITEMS (price/name snapshot - BR-04/05) ---------- */
CREATE TABLE dbo.ORDER_ITEMS
(
    ID                          UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY DEFAULT NEWID(),
    ORDER_ID                    UNIQUEIDENTIFIER NOT NULL,
    VARIANT_ID                  UNIQUEIDENTIFIER NOT NULL,
    PRODUCT_NAME_SNAPSHOT       NVARCHAR(300)    NOT NULL,
    VARIANT_SKU_SNAPSHOT        NVARCHAR(100)    NOT NULL,
    VARIANT_ATTRIBUTES_SNAPSHOT NVARCHAR(MAX)    NULL,
    UNIT_PRICE_SNAPSHOT         DECIMAL(18,2)    NOT NULL,
    QUANTITY                    INT              NOT NULL,
    LINE_TOTAL                  DECIMAL(18,2)    NOT NULL,
    CREATED_AT                  DATETIME2        NOT NULL CONSTRAINT DF_ORDER_ITEMS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY                  UNIQUEIDENTIFIER NULL,
    UPDATED_AT                  DATETIME2        NULL,
    UPDATED_BY                  UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_ORDER_ITEMS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEMS_VARIANTS FOREIGN KEY (VARIANT_ID) REFERENCES dbo.PRODUCT_VARIANTS(ID),
    CONSTRAINT CK_ORDER_ITEMS_QUANTITY CHECK (QUANTITY > 0)
);
GO

/* ---------- 12. PAYMENTS (TXN_REF = idempotency key - BR-13) ---------- */
CREATE TABLE dbo.PAYMENTS
(
    ID                    UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_PAYMENTS PRIMARY KEY DEFAULT NEWID(),
    ORDER_ID              UNIQUEIDENTIFIER NOT NULL,
    METHOD                VARCHAR(20)      NOT NULL,
    AMOUNT                DECIMAL(18,2)    NOT NULL,
    STATUS                VARCHAR(20)      NOT NULL CONSTRAINT DF_PAYMENTS_STATUS DEFAULT 'Pending',
    TXN_REF               NVARCHAR(100)    NULL,
    GATEWAY_RESPONSE_JSON NVARCHAR(MAX)    NULL,
    PAID_AT               DATETIME2        NULL,
    CREATED_AT            DATETIME2        NOT NULL CONSTRAINT DF_PAYMENTS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY            UNIQUEIDENTIFIER NULL,
    UPDATED_AT            DATETIME2        NULL,
    UPDATED_BY            UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_PAYMENTS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_PAYMENTS_METHOD CHECK (METHOD IN ('COD','VNPay','MoMo')),
    CONSTRAINT CK_PAYMENTS_STATUS CHECK (STATUS IN ('Pending','Processing','Success','Failed','Expired'))
);
GO

/* ---------- 13. SHIPMENTS ---------- */
CREATE TABLE dbo.SHIPMENTS
(
    ID              UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SHIPMENTS PRIMARY KEY DEFAULT NEWID(),
    ORDER_ID        UNIQUEIDENTIFIER NOT NULL,
    PROVIDER        VARCHAR(20)      NOT NULL,
    TRACKING_NUMBER NVARCHAR(100)    NULL,
    STATUS          VARCHAR(20)      NOT NULL CONSTRAINT DF_SHIPMENTS_STATUS DEFAULT 'Pending',
    SHIPPED_AT      DATETIME2        NULL,
    DELIVERED_AT    DATETIME2        NULL,
    COST_FEE        DECIMAL(18,2)    NULL,
    CREATED_AT      DATETIME2        NOT NULL CONSTRAINT DF_SHIPMENTS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY      UNIQUEIDENTIFIER NULL,
    UPDATED_AT      DATETIME2        NULL,
    UPDATED_BY      UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_SHIPMENTS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_SHIPMENTS_PROVIDER CHECK (PROVIDER IN ('GHTK','GHN'))
);
GO

/* ---------- 14. REVIEWS (1 review per ORDER_ITEM - BR-11) ---------- */
CREATE TABLE dbo.REVIEWS
(
    ID            UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_REVIEWS PRIMARY KEY DEFAULT NEWID(),
    PRODUCT_ID    UNIQUEIDENTIFIER NOT NULL,
    USER_ID       UNIQUEIDENTIFIER NOT NULL,
    ORDER_ITEM_ID UNIQUEIDENTIFIER NOT NULL,
    RATING        TINYINT          NOT NULL,
    COMMENT       NVARCHAR(2000)   NULL,
    IS_APPROVED   BIT              NOT NULL CONSTRAINT DF_REVIEWS_IS_APPROVED DEFAULT 0,
    CREATED_AT    DATETIME2        NOT NULL CONSTRAINT DF_REVIEWS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    CREATED_BY    UNIQUEIDENTIFIER NULL,
    UPDATED_AT    DATETIME2        NULL,
    UPDATED_BY    UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_REVIEWS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS(ID),
    CONSTRAINT FK_REVIEWS_USERS FOREIGN KEY (USER_ID) REFERENCES dbo.USERS(ID),
    CONSTRAINT FK_REVIEWS_ORDER_ITEMS FOREIGN KEY (ORDER_ITEM_ID) REFERENCES dbo.ORDER_ITEMS(ID),
    CONSTRAINT UQ_REVIEWS_ORDER_ITEM UNIQUE (ORDER_ITEM_ID),
    CONSTRAINT CK_REVIEWS_RATING CHECK (RATING BETWEEN 1 AND 5)
);
GO

/* ---------- 15. ORDER_AUDIT_LOGS (BR-14) ----------
   This table IS the audit trail; CHANGED_BY / CHANGED_AT capture who/when. */
CREATE TABLE dbo.ORDER_AUDIT_LOGS
(
    ID          UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ORDER_AUDIT_LOGS PRIMARY KEY DEFAULT NEWID(),
    ORDER_ID    UNIQUEIDENTIFIER NOT NULL,
    FROM_STATUS VARCHAR(20)      NULL,
    TO_STATUS   VARCHAR(20)      NOT NULL,
    CHANGED_BY  UNIQUEIDENTIFIER NULL,   -- NULL = system
    REASON      NVARCHAR(500)    NULL,
    CHANGED_AT  DATETIME2        NOT NULL CONSTRAINT DF_ORDER_AUDIT_LOGS_CHANGED_AT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ORDER_AUDIT_LOGS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_AUDIT_LOGS_USERS FOREIGN KEY (CHANGED_BY) REFERENCES dbo.USERS(ID)
);
GO

/* =====================================================================
   Indexes
   ===================================================================== */
CREATE INDEX IX_PRODUCTS_CATEGORY        ON dbo.PRODUCTS (CATEGORY_ID, IS_ACTIVE, IS_DELETED);
CREATE INDEX IX_PRODUCTS_NAME            ON dbo.PRODUCTS (NAME);
CREATE INDEX IX_PRODUCT_VARIANTS_PRODUCT ON dbo.PRODUCT_VARIANTS (PRODUCT_ID);
CREATE INDEX IX_ADDRESSES_USER           ON dbo.ADDRESSES (USER_ID);
CREATE INDEX IX_CARTS_USER               ON dbo.CARTS (USER_ID);
CREATE INDEX IX_CARTS_SESSION            ON dbo.CARTS (SESSION_ID);
CREATE INDEX IX_CART_ITEMS_CART          ON dbo.CART_ITEMS (CART_ID);
CREATE INDEX IX_ORDERS_USER              ON dbo.ORDERS (USER_ID, CREATED_AT DESC);
CREATE INDEX IX_ORDERS_STATUS            ON dbo.ORDERS (STATUS, CREATED_AT);
CREATE INDEX IX_ORDER_ITEMS_ORDER        ON dbo.ORDER_ITEMS (ORDER_ID);
CREATE INDEX IX_PAYMENTS_ORDER           ON dbo.PAYMENTS (ORDER_ID);
CREATE UNIQUE INDEX UX_PAYMENTS_TXN_REF  ON dbo.PAYMENTS (TXN_REF) WHERE TXN_REF IS NOT NULL;
CREATE INDEX IX_SHIPMENTS_ORDER          ON dbo.SHIPMENTS (ORDER_ID);
CREATE INDEX IX_REVIEWS_PRODUCT          ON dbo.REVIEWS (PRODUCT_ID, IS_APPROVED);
CREATE INDEX IX_ORDER_AUDIT_LOGS_ORDER   ON dbo.ORDER_AUDIT_LOGS (ORDER_ID);
GO
